name: ARM

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

# Building using the github runner environement directly.
jobs:
  arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci arm_env
    - name: Build devel image
      run: make --directory=ci arm_devel
    - name: Build project
      run: make --directory=ci arm_build
    - name: Test project
      run: make --directory=ci arm_test
