name: mips Toolchain

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  mips:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [
          [mips32],
          [mips32el],
          [mips64],
          [mips64el]
        ]
      fail-fast: false
    env:
      TARGET: ${{ matrix.targets[0] }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make --directory=ci ${TARGET}_build
    - name: Test
      run: make --directory=ci ${TARGET}_test
